### ISSUE TITLE
Undocumented/Unmet dependency: ctime.pl

### ISSUE THREAD

**Issue by 1977er** [mtsatsenko/imaputils#10]
iu-migrate and iu-maildirtoimap require a script called ctime.pl which is not shipped.

**Comment by mtsatsenko** [comment]
Thanks for reporting this. This appears to be a bug, I believe this is some kind of leftover code from very old version. In fact returning value of ctime() is never being used. So in my opinion it can safely be removed. I will do so tomorrow. Hope it helps
