### ISSUE TITLE
iu-migrate will skip users with a "#" in their password

### ISSUE THREAD

**Issue by danliston** [mtsatsenko/imaputils#6]
Line 660 (of iu-migrate) attempts to allow for a user in the -i list to be skipped, but is too greedy.  
The regex to match this use case should be /^#/ instead of just /#/
The "fix" is to change line 660 from
      next if /#/;
to
     next if /^#/;
A caveat to this fix is that a username that actually starts with a hash mark will also be skipped.

**Comment by mtsatsenko** [comment]
Hello,
Thanks for reporting this. Perhaps I will consider removing line 660 at all, but for now I just commit as you suggest
