### ISSUE TITLE
iu-copy ignores mails without message ID

### ISSUE THREAD

**Issue by daniel-mueller-3w-media-de** [mtsatsenko/imaputils#8]
Thanks to the last few lines of getMsgList in iu-copy, mails without message ID will be skipped. But mails in folders like "Sent Items" often don't have message IDs and will therefore be ignored. This happens whether update mode is used or not. I understand that message IDs are useful for identifying mails, but silently ignoring them is bad (iu-copy actually says "Sent Items mailbox is empty" instead of "Sent Items mailbox contains messages without ID that can not be copied" or something similar, giving the impression that everything is alright). imapcopy (see http://ardiehl.de/imapcopy/index.html) handles this correctly, but unfortunately has no update mode.

I don't know what the best solution would be (as updating without having unique identifiers is pretty hard). Maybe 1 or 2 additional options that allow to explicitly skip or copy mails without ID, independent of update mode. This would produce additional copies of ID-less mails, but I think that's better than ignoring them and being silent about it.

**Comment by mtsatsenko** [comment]
Well. Adding additional flags It makes sense. I will have more detailed look at this matter next days

**Comment by mtsatsenko** [comment]
Please see the latest commit. Not the most elegant solution, but I hope it will work for you.

**Comment by daniel-mueller-3w-media-de** [comment]
Looks good. Thanks a lot.
